/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sunlands.rpc.student.sv;


import org.apache.thrift.TEnum;

public enum Role implements TEnum {
  STUDENT(0),
  TEACHER(1);

  private final int value;

  private Role(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Role findByValue(int value) { 
    switch (value) {
      case 0:
        return STUDENT;
      case 1:
        return TEACHER;
      default:
        return null;
    }
  }
}
