/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sunlands.rpc.student.sv;

import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import javax.annotation.Generated;
import java.util.*;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-02-28")
public class termSubject implements org.apache.thrift.TBase<termSubject, termSubject._Fields>, java.io.Serializable, Cloneable, Comparable<termSubject> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("termSubject");

  private static final org.apache.thrift.protocol.TField TERM_FIELD_DESC = new org.apache.thrift.protocol.TField("term", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField CURRENT_TERM_FIELD_DESC = new org.apache.thrift.protocol.TField("currentTerm", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField TERM_SUBJECTS_FIELD_DESC = new org.apache.thrift.protocol.TField("termSubjects", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new termSubjectStandardSchemeFactory());
    schemes.put(TupleScheme.class, new termSubjectTupleSchemeFactory());
  }

  public int term; // required
  public int currentTerm; // required
  public List<Subject> termSubjects; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TERM((short)1, "term"),
    CURRENT_TERM((short)2, "currentTerm"),
    TERM_SUBJECTS((short)3, "termSubjects");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TERM
          return TERM;
        case 2: // CURRENT_TERM
          return CURRENT_TERM;
        case 3: // TERM_SUBJECTS
          return TERM_SUBJECTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TERM_ISSET_ID = 0;
  private static final int __CURRENTTERM_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TERM, new org.apache.thrift.meta_data.FieldMetaData("term", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CURRENT_TERM, new org.apache.thrift.meta_data.FieldMetaData("currentTerm", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TERM_SUBJECTS, new org.apache.thrift.meta_data.FieldMetaData("termSubjects", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Subject.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(termSubject.class, metaDataMap);
  }

  public termSubject() {
  }

  public termSubject(
    int term,
    int currentTerm,
    List<Subject> termSubjects)
  {
    this();
    this.term = term;
    setTermIsSet(true);
    this.currentTerm = currentTerm;
    setCurrentTermIsSet(true);
    this.termSubjects = termSubjects;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public termSubject(termSubject other) {
    __isset_bitfield = other.__isset_bitfield;
    this.term = other.term;
    this.currentTerm = other.currentTerm;
    if (other.isSetTermSubjects()) {
      List<Subject> __this__termSubjects = new ArrayList<Subject>(other.termSubjects.size());
      for (Subject other_element : other.termSubjects) {
        __this__termSubjects.add(new Subject(other_element));
      }
      this.termSubjects = __this__termSubjects;
    }
  }

  public termSubject deepCopy() {
    return new termSubject(this);
  }

  @Override
  public void clear() {
    setTermIsSet(false);
    this.term = 0;
    setCurrentTermIsSet(false);
    this.currentTerm = 0;
    this.termSubjects = null;
  }

  public int getTerm() {
    return this.term;
  }

  public termSubject setTerm(int term) {
    this.term = term;
    setTermIsSet(true);
    return this;
  }

  public void unsetTerm() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TERM_ISSET_ID);
  }

  /** Returns true if field term is set (has been assigned a value) and false otherwise */
  public boolean isSetTerm() {
    return EncodingUtils.testBit(__isset_bitfield, __TERM_ISSET_ID);
  }

  public void setTermIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TERM_ISSET_ID, value);
  }

  public int getCurrentTerm() {
    return this.currentTerm;
  }

  public termSubject setCurrentTerm(int currentTerm) {
    this.currentTerm = currentTerm;
    setCurrentTermIsSet(true);
    return this;
  }

  public void unsetCurrentTerm() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CURRENTTERM_ISSET_ID);
  }

  /** Returns true if field currentTerm is set (has been assigned a value) and false otherwise */
  public boolean isSetCurrentTerm() {
    return EncodingUtils.testBit(__isset_bitfield, __CURRENTTERM_ISSET_ID);
  }

  public void setCurrentTermIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CURRENTTERM_ISSET_ID, value);
  }

  public int getTermSubjectsSize() {
    return (this.termSubjects == null) ? 0 : this.termSubjects.size();
  }

  public java.util.Iterator<Subject> getTermSubjectsIterator() {
    return (this.termSubjects == null) ? null : this.termSubjects.iterator();
  }

  public void addToTermSubjects(Subject elem) {
    if (this.termSubjects == null) {
      this.termSubjects = new ArrayList<Subject>();
    }
    this.termSubjects.add(elem);
  }

  public List<Subject> getTermSubjects() {
    return this.termSubjects;
  }

  public termSubject setTermSubjects(List<Subject> termSubjects) {
    this.termSubjects = termSubjects;
    return this;
  }

  public void unsetTermSubjects() {
    this.termSubjects = null;
  }

  /** Returns true if field termSubjects is set (has been assigned a value) and false otherwise */
  public boolean isSetTermSubjects() {
    return this.termSubjects != null;
  }

  public void setTermSubjectsIsSet(boolean value) {
    if (!value) {
      this.termSubjects = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TERM:
      if (value == null) {
        unsetTerm();
      } else {
        setTerm((Integer)value);
      }
      break;

    case CURRENT_TERM:
      if (value == null) {
        unsetCurrentTerm();
      } else {
        setCurrentTerm((Integer)value);
      }
      break;

    case TERM_SUBJECTS:
      if (value == null) {
        unsetTermSubjects();
      } else {
        setTermSubjects((List<Subject>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TERM:
      return getTerm();

    case CURRENT_TERM:
      return getCurrentTerm();

    case TERM_SUBJECTS:
      return getTermSubjects();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TERM:
      return isSetTerm();
    case CURRENT_TERM:
      return isSetCurrentTerm();
    case TERM_SUBJECTS:
      return isSetTermSubjects();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof termSubject)
      return this.equals((termSubject)that);
    return false;
  }

  public boolean equals(termSubject that) {
    if (that == null)
      return false;

    boolean this_present_term = true;
    boolean that_present_term = true;
    if (this_present_term || that_present_term) {
      if (!(this_present_term && that_present_term))
        return false;
      if (this.term != that.term)
        return false;
    }

    boolean this_present_currentTerm = true;
    boolean that_present_currentTerm = true;
    if (this_present_currentTerm || that_present_currentTerm) {
      if (!(this_present_currentTerm && that_present_currentTerm))
        return false;
      if (this.currentTerm != that.currentTerm)
        return false;
    }

    boolean this_present_termSubjects = true && this.isSetTermSubjects();
    boolean that_present_termSubjects = true && that.isSetTermSubjects();
    if (this_present_termSubjects || that_present_termSubjects) {
      if (!(this_present_termSubjects && that_present_termSubjects))
        return false;
      if (!this.termSubjects.equals(that.termSubjects))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_term = true;
    list.add(present_term);
    if (present_term)
      list.add(term);

    boolean present_currentTerm = true;
    list.add(present_currentTerm);
    if (present_currentTerm)
      list.add(currentTerm);

    boolean present_termSubjects = true && (isSetTermSubjects());
    list.add(present_termSubjects);
    if (present_termSubjects)
      list.add(termSubjects);

    return list.hashCode();
  }

  @Override
  public int compareTo(termSubject other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTerm()).compareTo(other.isSetTerm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTerm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.term, other.term);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCurrentTerm()).compareTo(other.isSetCurrentTerm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCurrentTerm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.currentTerm, other.currentTerm);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTermSubjects()).compareTo(other.isSetTermSubjects());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTermSubjects()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.termSubjects, other.termSubjects);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("termSubject(");
    boolean first = true;

    sb.append("term:");
    sb.append(this.term);
    first = false;
    if (!first) sb.append(", ");
    sb.append("currentTerm:");
    sb.append(this.currentTerm);
    first = false;
    if (!first) sb.append(", ");
    sb.append("termSubjects:");
    if (this.termSubjects == null) {
      sb.append("null");
    } else {
      sb.append(this.termSubjects);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class termSubjectStandardSchemeFactory implements SchemeFactory {
    public termSubjectStandardScheme getScheme() {
      return new termSubjectStandardScheme();
    }
  }

  private static class termSubjectStandardScheme extends StandardScheme<termSubject> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, termSubject struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TERM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.term = iprot.readI32();
              struct.setTermIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CURRENT_TERM
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.currentTerm = iprot.readI32();
              struct.setCurrentTermIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TERM_SUBJECTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.termSubjects = new ArrayList<Subject>(_list16.size);
                Subject _elem17;
                for (int _i18 = 0; _i18 < _list16.size; ++_i18)
                {
                  _elem17 = new Subject();
                  _elem17.read(iprot);
                  struct.termSubjects.add(_elem17);
                }
                iprot.readListEnd();
              }
              struct.setTermSubjectsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, termSubject struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TERM_FIELD_DESC);
      oprot.writeI32(struct.term);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CURRENT_TERM_FIELD_DESC);
      oprot.writeI32(struct.currentTerm);
      oprot.writeFieldEnd();
      if (struct.termSubjects != null) {
        oprot.writeFieldBegin(TERM_SUBJECTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.termSubjects.size()));
          for (Subject _iter19 : struct.termSubjects)
          {
            _iter19.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class termSubjectTupleSchemeFactory implements SchemeFactory {
    public termSubjectTupleScheme getScheme() {
      return new termSubjectTupleScheme();
    }
  }

  private static class termSubjectTupleScheme extends TupleScheme<termSubject> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, termSubject struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTerm()) {
        optionals.set(0);
      }
      if (struct.isSetCurrentTerm()) {
        optionals.set(1);
      }
      if (struct.isSetTermSubjects()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetTerm()) {
        oprot.writeI32(struct.term);
      }
      if (struct.isSetCurrentTerm()) {
        oprot.writeI32(struct.currentTerm);
      }
      if (struct.isSetTermSubjects()) {
        {
          oprot.writeI32(struct.termSubjects.size());
          for (Subject _iter20 : struct.termSubjects)
          {
            _iter20.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, termSubject struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.term = iprot.readI32();
        struct.setTermIsSet(true);
      }
      if (incoming.get(1)) {
        struct.currentTerm = iprot.readI32();
        struct.setCurrentTermIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.termSubjects = new ArrayList<Subject>(_list21.size);
          Subject _elem22;
          for (int _i23 = 0; _i23 < _list21.size; ++_i23)
          {
            _elem22 = new Subject();
            _elem22.read(iprot);
            struct.termSubjects.add(_elem22);
          }
        }
        struct.setTermSubjectsIsSet(true);
      }
    }
  }

}

