/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sunlands.rpc.web.statistics.service;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-07-11")
public class UnitsStatisticCondition implements org.apache.thrift.TBase<UnitsStatisticCondition, UnitsStatisticCondition._Fields>, java.io.Serializable, Cloneable, Comparable<UnitsStatisticCondition> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UnitsStatisticCondition");

  private static final org.apache.thrift.protocol.TField ROUND_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("roundId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField TEACH_UNIT_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("teachUnitIds", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TEACHER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("teacherId", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new UnitsStatisticConditionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new UnitsStatisticConditionTupleSchemeFactory());
  }

  public int roundId; // required
  public String teachUnitIds; // required
  public int teacherId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ROUND_ID((short)1, "roundId"),
    TEACH_UNIT_IDS((short)2, "teachUnitIds"),
    TEACHER_ID((short)3, "teacherId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ROUND_ID
          return ROUND_ID;
        case 2: // TEACH_UNIT_IDS
          return TEACH_UNIT_IDS;
        case 3: // TEACHER_ID
          return TEACHER_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ROUNDID_ISSET_ID = 0;
  private static final int __TEACHERID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ROUND_ID, new org.apache.thrift.meta_data.FieldMetaData("roundId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TEACH_UNIT_IDS, new org.apache.thrift.meta_data.FieldMetaData("teachUnitIds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TEACHER_ID, new org.apache.thrift.meta_data.FieldMetaData("teacherId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UnitsStatisticCondition.class, metaDataMap);
  }

  public UnitsStatisticCondition() {
  }

  public UnitsStatisticCondition(
    int roundId,
    String teachUnitIds,
    int teacherId)
  {
    this();
    this.roundId = roundId;
    setRoundIdIsSet(true);
    this.teachUnitIds = teachUnitIds;
    this.teacherId = teacherId;
    setTeacherIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UnitsStatisticCondition(UnitsStatisticCondition other) {
    __isset_bitfield = other.__isset_bitfield;
    this.roundId = other.roundId;
    if (other.isSetTeachUnitIds()) {
      this.teachUnitIds = other.teachUnitIds;
    }
    this.teacherId = other.teacherId;
  }

  public UnitsStatisticCondition deepCopy() {
    return new UnitsStatisticCondition(this);
  }

  @Override
  public void clear() {
    setRoundIdIsSet(false);
    this.roundId = 0;
    this.teachUnitIds = null;
    setTeacherIdIsSet(false);
    this.teacherId = 0;
  }

  public int getRoundId() {
    return this.roundId;
  }

  public UnitsStatisticCondition setRoundId(int roundId) {
    this.roundId = roundId;
    setRoundIdIsSet(true);
    return this;
  }

  public void unsetRoundId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ROUNDID_ISSET_ID);
  }

  /** Returns true if field roundId is set (has been assigned a value) and false otherwise */
  public boolean isSetRoundId() {
    return EncodingUtils.testBit(__isset_bitfield, __ROUNDID_ISSET_ID);
  }

  public void setRoundIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ROUNDID_ISSET_ID, value);
  }

  public String getTeachUnitIds() {
    return this.teachUnitIds;
  }

  public UnitsStatisticCondition setTeachUnitIds(String teachUnitIds) {
    this.teachUnitIds = teachUnitIds;
    return this;
  }

  public void unsetTeachUnitIds() {
    this.teachUnitIds = null;
  }

  /** Returns true if field teachUnitIds is set (has been assigned a value) and false otherwise */
  public boolean isSetTeachUnitIds() {
    return this.teachUnitIds != null;
  }

  public void setTeachUnitIdsIsSet(boolean value) {
    if (!value) {
      this.teachUnitIds = null;
    }
  }

  public int getTeacherId() {
    return this.teacherId;
  }

  public UnitsStatisticCondition setTeacherId(int teacherId) {
    this.teacherId = teacherId;
    setTeacherIdIsSet(true);
    return this;
  }

  public void unsetTeacherId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TEACHERID_ISSET_ID);
  }

  /** Returns true if field teacherId is set (has been assigned a value) and false otherwise */
  public boolean isSetTeacherId() {
    return EncodingUtils.testBit(__isset_bitfield, __TEACHERID_ISSET_ID);
  }

  public void setTeacherIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TEACHERID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ROUND_ID:
      if (value == null) {
        unsetRoundId();
      } else {
        setRoundId((Integer)value);
      }
      break;

    case TEACH_UNIT_IDS:
      if (value == null) {
        unsetTeachUnitIds();
      } else {
        setTeachUnitIds((String)value);
      }
      break;

    case TEACHER_ID:
      if (value == null) {
        unsetTeacherId();
      } else {
        setTeacherId((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ROUND_ID:
      return getRoundId();

    case TEACH_UNIT_IDS:
      return getTeachUnitIds();

    case TEACHER_ID:
      return getTeacherId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ROUND_ID:
      return isSetRoundId();
    case TEACH_UNIT_IDS:
      return isSetTeachUnitIds();
    case TEACHER_ID:
      return isSetTeacherId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UnitsStatisticCondition)
      return this.equals((UnitsStatisticCondition)that);
    return false;
  }

  public boolean equals(UnitsStatisticCondition that) {
    if (that == null)
      return false;

    boolean this_present_roundId = true;
    boolean that_present_roundId = true;
    if (this_present_roundId || that_present_roundId) {
      if (!(this_present_roundId && that_present_roundId))
        return false;
      if (this.roundId != that.roundId)
        return false;
    }

    boolean this_present_teachUnitIds = true && this.isSetTeachUnitIds();
    boolean that_present_teachUnitIds = true && that.isSetTeachUnitIds();
    if (this_present_teachUnitIds || that_present_teachUnitIds) {
      if (!(this_present_teachUnitIds && that_present_teachUnitIds))
        return false;
      if (!this.teachUnitIds.equals(that.teachUnitIds))
        return false;
    }

    boolean this_present_teacherId = true;
    boolean that_present_teacherId = true;
    if (this_present_teacherId || that_present_teacherId) {
      if (!(this_present_teacherId && that_present_teacherId))
        return false;
      if (this.teacherId != that.teacherId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_roundId = true;
    list.add(present_roundId);
    if (present_roundId)
      list.add(roundId);

    boolean present_teachUnitIds = true && (isSetTeachUnitIds());
    list.add(present_teachUnitIds);
    if (present_teachUnitIds)
      list.add(teachUnitIds);

    boolean present_teacherId = true;
    list.add(present_teacherId);
    if (present_teacherId)
      list.add(teacherId);

    return list.hashCode();
  }

  @Override
  public int compareTo(UnitsStatisticCondition other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRoundId()).compareTo(other.isSetRoundId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoundId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roundId, other.roundId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTeachUnitIds()).compareTo(other.isSetTeachUnitIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTeachUnitIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.teachUnitIds, other.teachUnitIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTeacherId()).compareTo(other.isSetTeacherId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTeacherId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.teacherId, other.teacherId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UnitsStatisticCondition(");
    boolean first = true;

    sb.append("roundId:");
    sb.append(this.roundId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("teachUnitIds:");
    if (this.teachUnitIds == null) {
      sb.append("null");
    } else {
      sb.append(this.teachUnitIds);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("teacherId:");
    sb.append(this.teacherId);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UnitsStatisticConditionStandardSchemeFactory implements SchemeFactory {
    public UnitsStatisticConditionStandardScheme getScheme() {
      return new UnitsStatisticConditionStandardScheme();
    }
  }

  private static class UnitsStatisticConditionStandardScheme extends StandardScheme<UnitsStatisticCondition> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UnitsStatisticCondition struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ROUND_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.roundId = iprot.readI32();
              struct.setRoundIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TEACH_UNIT_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.teachUnitIds = iprot.readString();
              struct.setTeachUnitIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TEACHER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.teacherId = iprot.readI32();
              struct.setTeacherIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UnitsStatisticCondition struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ROUND_ID_FIELD_DESC);
      oprot.writeI32(struct.roundId);
      oprot.writeFieldEnd();
      if (struct.teachUnitIds != null) {
        oprot.writeFieldBegin(TEACH_UNIT_IDS_FIELD_DESC);
        oprot.writeString(struct.teachUnitIds);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TEACHER_ID_FIELD_DESC);
      oprot.writeI32(struct.teacherId);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UnitsStatisticConditionTupleSchemeFactory implements SchemeFactory {
    public UnitsStatisticConditionTupleScheme getScheme() {
      return new UnitsStatisticConditionTupleScheme();
    }
  }

  private static class UnitsStatisticConditionTupleScheme extends TupleScheme<UnitsStatisticCondition> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UnitsStatisticCondition struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRoundId()) {
        optionals.set(0);
      }
      if (struct.isSetTeachUnitIds()) {
        optionals.set(1);
      }
      if (struct.isSetTeacherId()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetRoundId()) {
        oprot.writeI32(struct.roundId);
      }
      if (struct.isSetTeachUnitIds()) {
        oprot.writeString(struct.teachUnitIds);
      }
      if (struct.isSetTeacherId()) {
        oprot.writeI32(struct.teacherId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UnitsStatisticCondition struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.roundId = iprot.readI32();
        struct.setRoundIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.teachUnitIds = iprot.readString();
        struct.setTeachUnitIdsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.teacherId = iprot.readI32();
        struct.setTeacherIdIsSet(true);
      }
    }
  }

}

