spring:
      profiles: dev
      redis:
           host: 172.16.116.9
           port: 9736
           database: 1
           expires: 1500
           pool:
               max-idle: 100
               min-idle: 0
               max-active: 100
               max-wait: -1
      aop:
           proxy-target-class: true
      datasource:
           type: com.alibaba.druid.pool.DruidDataSource
           master:
               url: jdbc:mysql://172.16.117.226:3306/exercise
               username: ent_all
               password: ent
               driver-class-name: com.mysql.jdbc.Driver
               minIdle: 5
               maxActive: 100
               initialSize: 10
               maxWait: 60000
               timeBetweenEvictionRunsMillis: 60000
               minEvictableIdleTimeMillis: 300000
               validationQuery: select 'x'
               testWhileIdle: true
               testOnBorrow: false
               testOnReturn: false
               poolPreparedStatements: true
               maxPoolPreparedStatementPerConnectionSize: 50
               removeAbandoned: true
               filters: stat
           slave:
               url: jdbc:mysql://172.16.116.136:3307/exercise
               username: ent_all
               password: ent
               driver-class-name: com.mysql.jdbc.Driver
               minIdle: 5
               maxActive: 100
               initialSize: 10
               maxWait: 60000
               timeBetweenEvictionRunsMillis: 60000
               minEvictableIdleTimeMillis: 300000
               validationQuery: select 'x'
               testWhileIdle: true
               testOnBorrow: false
               testOnReturn: false
               poolPreparedStatements: true
               maxPoolPreparedStatementPerConnectionSize: 50
               removeAbandoned: true
               filters: stat
server:
      port: 9094
logging:
    level:
        com.sunlands: DEBUG

rpc:
    student-rpc-url: http://172.16.100.203:9094/student
