/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sunlands.rpc.web.coursetemplate.service;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-05-21")
public class KnowledgeTree implements org.apache.thrift.TBase<KnowledgeTree, KnowledgeTree._Fields>, java.io.Serializable, Cloneable, Comparable<KnowledgeTree> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("KnowledgeTree");

  private static final org.apache.thrift.protocol.TField KNOWLEDGE_TREE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("knowledgeTreeId", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField SUBJECT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("subjectId", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField PROVINCES_FIELD_DESC = new org.apache.thrift.protocol.TField("provinces", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new KnowledgeTreeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new KnowledgeTreeTupleSchemeFactory());
  }

  public int knowledgeTreeId; // required
  public int subjectId; // required
  public String provinces; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    KNOWLEDGE_TREE_ID((short)1, "knowledgeTreeId"),
    SUBJECT_ID((short)2, "subjectId"),
    PROVINCES((short)3, "provinces");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // KNOWLEDGE_TREE_ID
          return KNOWLEDGE_TREE_ID;
        case 2: // SUBJECT_ID
          return SUBJECT_ID;
        case 3: // PROVINCES
          return PROVINCES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __KNOWLEDGETREEID_ISSET_ID = 0;
  private static final int __SUBJECTID_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.KNOWLEDGE_TREE_ID, new org.apache.thrift.meta_data.FieldMetaData("knowledgeTreeId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SUBJECT_ID, new org.apache.thrift.meta_data.FieldMetaData("subjectId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PROVINCES, new org.apache.thrift.meta_data.FieldMetaData("provinces", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(KnowledgeTree.class, metaDataMap);
  }

  public KnowledgeTree() {
  }

  public KnowledgeTree(
    int knowledgeTreeId,
    int subjectId,
    String provinces)
  {
    this();
    this.knowledgeTreeId = knowledgeTreeId;
    setKnowledgeTreeIdIsSet(true);
    this.subjectId = subjectId;
    setSubjectIdIsSet(true);
    this.provinces = provinces;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public KnowledgeTree(KnowledgeTree other) {
    __isset_bitfield = other.__isset_bitfield;
    this.knowledgeTreeId = other.knowledgeTreeId;
    this.subjectId = other.subjectId;
    if (other.isSetProvinces()) {
      this.provinces = other.provinces;
    }
  }

  public KnowledgeTree deepCopy() {
    return new KnowledgeTree(this);
  }

  @Override
  public void clear() {
    setKnowledgeTreeIdIsSet(false);
    this.knowledgeTreeId = 0;
    setSubjectIdIsSet(false);
    this.subjectId = 0;
    this.provinces = null;
  }

  public int getKnowledgeTreeId() {
    return this.knowledgeTreeId;
  }

  public KnowledgeTree setKnowledgeTreeId(int knowledgeTreeId) {
    this.knowledgeTreeId = knowledgeTreeId;
    setKnowledgeTreeIdIsSet(true);
    return this;
  }

  public void unsetKnowledgeTreeId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __KNOWLEDGETREEID_ISSET_ID);
  }

  /** Returns true if field knowledgeTreeId is set (has been assigned a value) and false otherwise */
  public boolean isSetKnowledgeTreeId() {
    return EncodingUtils.testBit(__isset_bitfield, __KNOWLEDGETREEID_ISSET_ID);
  }

  public void setKnowledgeTreeIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __KNOWLEDGETREEID_ISSET_ID, value);
  }

  public int getSubjectId() {
    return this.subjectId;
  }

  public KnowledgeTree setSubjectId(int subjectId) {
    this.subjectId = subjectId;
    setSubjectIdIsSet(true);
    return this;
  }

  public void unsetSubjectId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUBJECTID_ISSET_ID);
  }

  /** Returns true if field subjectId is set (has been assigned a value) and false otherwise */
  public boolean isSetSubjectId() {
    return EncodingUtils.testBit(__isset_bitfield, __SUBJECTID_ISSET_ID);
  }

  public void setSubjectIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUBJECTID_ISSET_ID, value);
  }

  public String getProvinces() {
    return this.provinces;
  }

  public KnowledgeTree setProvinces(String provinces) {
    this.provinces = provinces;
    return this;
  }

  public void unsetProvinces() {
    this.provinces = null;
  }

  /** Returns true if field provinces is set (has been assigned a value) and false otherwise */
  public boolean isSetProvinces() {
    return this.provinces != null;
  }

  public void setProvincesIsSet(boolean value) {
    if (!value) {
      this.provinces = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case KNOWLEDGE_TREE_ID:
      if (value == null) {
        unsetKnowledgeTreeId();
      } else {
        setKnowledgeTreeId((Integer)value);
      }
      break;

    case SUBJECT_ID:
      if (value == null) {
        unsetSubjectId();
      } else {
        setSubjectId((Integer)value);
      }
      break;

    case PROVINCES:
      if (value == null) {
        unsetProvinces();
      } else {
        setProvinces((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case KNOWLEDGE_TREE_ID:
      return getKnowledgeTreeId();

    case SUBJECT_ID:
      return getSubjectId();

    case PROVINCES:
      return getProvinces();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case KNOWLEDGE_TREE_ID:
      return isSetKnowledgeTreeId();
    case SUBJECT_ID:
      return isSetSubjectId();
    case PROVINCES:
      return isSetProvinces();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof KnowledgeTree)
      return this.equals((KnowledgeTree)that);
    return false;
  }

  public boolean equals(KnowledgeTree that) {
    if (that == null)
      return false;

    boolean this_present_knowledgeTreeId = true;
    boolean that_present_knowledgeTreeId = true;
    if (this_present_knowledgeTreeId || that_present_knowledgeTreeId) {
      if (!(this_present_knowledgeTreeId && that_present_knowledgeTreeId))
        return false;
      if (this.knowledgeTreeId != that.knowledgeTreeId)
        return false;
    }

    boolean this_present_subjectId = true;
    boolean that_present_subjectId = true;
    if (this_present_subjectId || that_present_subjectId) {
      if (!(this_present_subjectId && that_present_subjectId))
        return false;
      if (this.subjectId != that.subjectId)
        return false;
    }

    boolean this_present_provinces = true && this.isSetProvinces();
    boolean that_present_provinces = true && that.isSetProvinces();
    if (this_present_provinces || that_present_provinces) {
      if (!(this_present_provinces && that_present_provinces))
        return false;
      if (!this.provinces.equals(that.provinces))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_knowledgeTreeId = true;
    list.add(present_knowledgeTreeId);
    if (present_knowledgeTreeId)
      list.add(knowledgeTreeId);

    boolean present_subjectId = true;
    list.add(present_subjectId);
    if (present_subjectId)
      list.add(subjectId);

    boolean present_provinces = true && (isSetProvinces());
    list.add(present_provinces);
    if (present_provinces)
      list.add(provinces);

    return list.hashCode();
  }

  @Override
  public int compareTo(KnowledgeTree other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetKnowledgeTreeId()).compareTo(other.isSetKnowledgeTreeId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKnowledgeTreeId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.knowledgeTreeId, other.knowledgeTreeId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSubjectId()).compareTo(other.isSetSubjectId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSubjectId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.subjectId, other.subjectId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProvinces()).compareTo(other.isSetProvinces());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProvinces()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.provinces, other.provinces);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("KnowledgeTree(");
    boolean first = true;

    sb.append("knowledgeTreeId:");
    sb.append(this.knowledgeTreeId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("subjectId:");
    sb.append(this.subjectId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("provinces:");
    if (this.provinces == null) {
      sb.append("null");
    } else {
      sb.append(this.provinces);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class KnowledgeTreeStandardSchemeFactory implements SchemeFactory {
    public KnowledgeTreeStandardScheme getScheme() {
      return new KnowledgeTreeStandardScheme();
    }
  }

  private static class KnowledgeTreeStandardScheme extends StandardScheme<KnowledgeTree> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, KnowledgeTree struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // KNOWLEDGE_TREE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.knowledgeTreeId = iprot.readI32();
              struct.setKnowledgeTreeIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SUBJECT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.subjectId = iprot.readI32();
              struct.setSubjectIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PROVINCES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.provinces = iprot.readString();
              struct.setProvincesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, KnowledgeTree struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(KNOWLEDGE_TREE_ID_FIELD_DESC);
      oprot.writeI32(struct.knowledgeTreeId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SUBJECT_ID_FIELD_DESC);
      oprot.writeI32(struct.subjectId);
      oprot.writeFieldEnd();
      if (struct.provinces != null) {
        oprot.writeFieldBegin(PROVINCES_FIELD_DESC);
        oprot.writeString(struct.provinces);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class KnowledgeTreeTupleSchemeFactory implements SchemeFactory {
    public KnowledgeTreeTupleScheme getScheme() {
      return new KnowledgeTreeTupleScheme();
    }
  }

  private static class KnowledgeTreeTupleScheme extends TupleScheme<KnowledgeTree> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, KnowledgeTree struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetKnowledgeTreeId()) {
        optionals.set(0);
      }
      if (struct.isSetSubjectId()) {
        optionals.set(1);
      }
      if (struct.isSetProvinces()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetKnowledgeTreeId()) {
        oprot.writeI32(struct.knowledgeTreeId);
      }
      if (struct.isSetSubjectId()) {
        oprot.writeI32(struct.subjectId);
      }
      if (struct.isSetProvinces()) {
        oprot.writeString(struct.provinces);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, KnowledgeTree struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.knowledgeTreeId = iprot.readI32();
        struct.setKnowledgeTreeIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.subjectId = iprot.readI32();
        struct.setSubjectIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.provinces = iprot.readString();
        struct.setProvincesIsSet(true);
      }
    }
  }

}

